**BROADCASTING**

A Mechanism That Allow Numpy To Perform Arithmetic Operations On Arrays Of Different Shapes And Sizes Without Explictly Copying Data.

Broadcasting Automatically Expands Smaller Arrays So They Can Match The Shape Of Larger Arrays During Operations.

In [3]:
import numpy as np

1. **To Perform Element-Wise Addition Using Broadcasting**

In [ ]:
x=np.array([1,2,3])
y=np.array([[10],[20],[30]])
print(x+y)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


2. **To Create 2D Array x Of Shape(3,4) And A 1D Array Of Shape(4,) Using Broadcasting**

In [ ]:
x=np.array([[5,6,7,8],[1,2,3,4],[9,10,11,12]])
y=np.array([1,2,3,4])
print(x-y)

[[4 4 4 4]
 [0 0 0 0]
 [8 8 8 8]]


3. **To Multiply A 3D Array Of Shape(2,3,4) by A 1D Array Of Shape(4,) Using Broadcasting**

In [ ]:
a = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],

              [[13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]]])
b=np.array([2,3,4,5])
print(a*b)

[[[  2   6  12  20]
  [ 10  18  28  40]
  [ 18  30  44  60]]

 [[ 26  42  60  80]
  [ 34  54  76 100]
  [ 42  66  92 120]]]


4. **To Add A Scalar Value To A 2D Array Of Shape(5,5)**

In [ ]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25]])
scal=10
print(arr+scal)

5. **To Reshape Two Arrays To Make Them Broadcast Compatible And Perform Element-Wise Multiplication.**

In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6,7,8,9])
xshape=x.reshape(3,1)
yshape=y.reshape(1,6)
print(xshape+yshape)

[[ 5  6  7  8  9 10]
 [ 6  7  8  9 10 11]
 [ 7  8  9 10 11 12]]


6. **To Divide Each Coloumn Of A 2D Array x Of Shape(4,3) By A 1D Array y Of Shape(4,)**

In [ ]:
x=np.array([[8,16,24],
            [2,4,6],
            [12,24,36],
            [4,8,12]])
y=np.array([2,2,3,4])
yshape=y.reshape(4,1)
print(x/yshape)

7. **Given A 2D Array Of Shape(3,5) And A 1D Array Of Shape(3,).Program To Transposes The 2D Array And Add The 1D Array To Each Row Of The Transposed Array**

In [5]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [1,12,13,14,15]])
arr1=np.array([1,2,3])
transarr=np.transpose(arr)
print(transarr+arr1)

[[ 2  8  4]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]
 [ 6 12 18]]


8. **To Substract A 1D Array y Of Shape (3,) From Each 2D Slice Of A 3D Array x Of Shape (2,3,4)**

In [7]:
arr=np.array([[[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]],
               [[13,14,15,16],
                [17,18,19,20],
                [21,22,23,24]]])
arr1=np.array([1,2,3])
print(arr-arr1[:,np.newaxis])

[[[ 0  1  2  3]
  [ 3  4  5  6]
  [ 6  7  8  9]]

 [[12 13 14 15]
  [15 16 17 18]
  [18 19 20 21]]]


9. **Create Two 1D Array x Of Shape (5,) And y Of Shape (5,). Reshape Them To (5,1) And (1,5) Respectively And Perform Element-Wise Addition**

In [8]:
x=np.array([1,2,3,4,5])
y=np.array([10,20,30,40,50])
rex=x.reshape((5,1))
rey=y.reshape((1,5))
print(rex+rey)

[[11 21 31 41 51]
 [12 22 32 42 52]
 [13 23 33 43 53]
 [14 24 34 44 54]
 [15 25 35 45 55]]


10. **Create A 2D Array x Of Shape (4,4) And A Scalar y.Perform Element-Wise Multiplication Of a And b**

In [9]:
x=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [13,14,15,16]])
y=3
print(x*y)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]]
