In [1]:
import numpy as np

1. **To Compute Logarithm Of The Sum Of Exponentations Of The Inputs,Sum Of Exponentiatios Of The Input In Base-2**

np.logaddexp()->Performs The Computation Of log(exp(x1​)+exp(x2​))

np.logaddexp2()->Base-2 Logarithm Version Of np.logaddexp().Performs The Computation Of log2(2^x1+2^x2)

In [ ]:
l1=np.log(1e-50)
l2=np.log(2.5e-50)
print("Logarithm Of The Sum Of Exponentiations:")
print(np.logaddexp(l1,l2))
print(np.logaddexp2(l1,l2))

Logarithm Of The Sum Of Exponentiations:
-113.87649168120691
-113.59955522772194


2. **To Get True Division Of The Element-Wise Array Inputs**

np.true_divide()->Performs True (floating-point) Division Element-wise Ensuring That The Result Is Always A Float,Even If The Inputs Are Integers

In [ ]:
x=np.arange(10)
print(np.true_divide(x,3))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


3. **To Get The Largest Integer Smaller Or Equal To The Division Of The Inputs**

np.floor_divide()->Performs Element-wise Floor Division

In [ ]:
x=[1.,2.,3.,4.]
print(np.floor_divide(x,1.5))

[0. 1. 2. 2.]


4. **To Get The Powers Of An Array Values Elements-Wise**

In [2]:
x=np.arange(7)
print(np.power(x,2))

[ 0  1  4  9 16 25 36]


5. **To Get Element-Wise Remainder Of Array Elements**

In [3]:
x=np.arange(7)
print(np.remainder(x,5))

[0 1 2 3 4 0 1]


6. **To Multiply A 5x3 Matrix By A 3x2 Matrix And Create A Real Matrix Product**

In [4]:
x=np.random.random((5,3))
y=np.random.random((3,2))
print(np.dot(x,y))

[[1.04861855 0.68885478]
 [0.55455811 0.6169618 ]
 [1.08805229 0.83701785]
 [0.59532352 0.40336736]
 [1.54351059 0.80836069]]


7. **To Multiply A Matrix By Another Matrix Of Complex Numbers And Create A New Matrix Of Complex Number**

In [7]:
x=np.array([1+2j,7+8j])
y=np.array([5+6j,7+8j])
print(np.vdot(x,y))

(130-4j)


8. **To Create An Inner Product Of Two Arrays**

In [8]:
x=np.arange(24).reshape((2,3,4))
y=np.arange(4)
print(np.inner(x,y))

[[ 14  38  62]
 [ 86 110 134]]


9. **To Generate Inner,Outer And Cross Products Of Matrices And Vectors**

In [9]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))


10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


10. **To Generate A Matrix Product Of Two Arrays**

In [11]:
x=[[1,0],[1,1]]
y=[[3,1],[2,2]]
print(np.matmul(x,y))

[[3 1]
 [5 3]]


11. **To Find The Roots Of The Following Polynomials**

In [12]:
print(np.roots([1,-2,1]))
print(np.roots([1,-12,10,7,-10]))

[1. 1.]
[11.04461946+0.j        -0.8711421 +0.j         0.91326132+0.4531004j
  0.91326132-0.4531004j]


12. **To Compute The Following Polynomial Values**

np.polyval()->To Evaluate A Polynomial At Specific Values Of x

In [13]:
print(np.polyval([1,-2,1],2))
print(np.polyval([1,-12,10,7,-10],3))

1
-142


13. **To Add One Polynomial To Another,Substract One Polynomial From Another,Multiply One Polynomial With Another And Divide One Polynomial By Another**

In [14]:
from numpy.polynomial import polynomial as P
x=(10,20,30)
y=(30,40,50)
print(P.polyadd(x,y))
print(P.polysub(x,y))
print(P.polymul(x,y))
print(P.polydiv(x,y))

[40. 60. 80.]
[-20. -20. -20.]
[ 300. 1000. 2200. 2200. 1500.]
(array([0.6]), array([-8., -4.]))


14. **To Compute The Trigonometeric sine,cosine and tangent array Of Angles In Degrees**

In [16]:
print("sine:",np.sin(np.array((0.,30.,45.,60.,90.))*np.pi/180.),"\n")
print("cosine:",np.cos(np.array((0.,30.,45.,60.,90.))*np.pi/180.),"\n")
print("tangent:",np.tan(np.array((0.,30.,45.,60.,90.))*np.pi/180.),"\n")

sine: [0.         0.5        0.70710678 0.8660254  1.        ] 

cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17] 

tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16] 



15. **To Calculate Inverse sine,cos and tangent For All Elements In A Given Array**

In [17]:
x=np.array([-1.,0,1.])
print("Inverse Sine:",np.arcsin(x),"\n")
print("Inverse Cosine:",np.arccos(x),"\n")
print("Inverse Tangent:",np.arctan(x))


Inverse Sine: [-1.57079633  0.          1.57079633] 

Inverse Cosine: [3.14159265 1.57079633 0.        ] 

Inverse Tangent: [-0.78539816  0.          0.78539816]
